[api]
enabled = true
address = "0.0.0.0:8686"

# [sources.demo_logs]
# type = "demo_logs"
# interval = 1.0
# format = "json"

[sources.my_source_id]
type = "prometheus_remote_write"
address = "0.0.0.0:5050"

# [sources.my_source_id]
# type = "http_client"
# endpoint = "https://sv3-api05.av.pan.local/v3/sample/healthcheck"
#   [sources.my_source_id.tls]
#   verify_certificate=false


# [transforms.modify]
# type = "remap"
# inputs = ["my_source_id"]
# source = '''
# . = parse_key_value!(.message)
# '''


# [transforms.my_transform_id]
# type = "log_to_metric"
# inputs = [ "my_source_id" ]

#   [[transforms.my_transform_id.metrics]]
#   type = "set"
#   field = "message"
#   name = "mimir-status"
#   increment_by_value = true

#     [transforms.my_transform_id.metrics.tags]
#     host = "test"

# [sources.my_source_id]
# type = "opentelemetry"

#   [sources.my_source_id.grpc]
#   address = "0.0.0.0:4317"

#   [sources.my_source_id.http]
#   address = "0.0.0.0:4318"

# [transforms.modify]
# type = "remap"
# inputs = ["my_source_id"]
# source = '''
# . = parse_key_value!(.message)

# [transforms.my_transform_id]
# type = "filter"
# # inputs = [ "modify" ]
# inputs = ['my_source_id']
# condition = '.name != "job:pg_gupta_testing_gke:rate" || .name !="job:gupta_testing_gke:rate"'


[sinks.my_sink_id]
type = "console"
inputs = [ "my_source_id" ]
target = "stdout"

  [sinks.my_sink_id.encoding]
  codec = "json"

